load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@bazel_env.bzl", "bazel_env")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

# The ESM marker ("type": "module") for everything compiled under apps/.
js_library(
    name = "package_json",
    srcs = ["package.json"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "biome_json",
    srcs = ["biome.json"],
    visibility = ["//visibility:public"],
)

alias(
    name = "format",
    actual = "//tools:format",
)

test_suite(
    name = "lint",
    tests = ["//apps/patka:lint"],
)

bazel_env(
    name = "env",
    tools = {
        "ant": "@ant_cli//:ant",
        "node": "@nodejs_host//:node_bin",
        "npm": "@nodejs_host//:npm",
    },
)
