load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:vitest/package_json.bzl", vitest_bin = "bin")

ts_project(
    name = "lib",
    srcs = glob(
        ["*.ts"],
        exclude = ["*.spec.ts"],
    ),
    transpiler = "tsc",
    tsconfig = "tsconfig.json",
    deps = [
        "//:package_json",
        "//:node_modules/@types/node",
        "//:node_modules/rxjs",
    ],
)

js_binary(
    name = "patka",
    data = [
        ":lib",
        "//:package_json",
        "//:node_modules/rxjs",
    ],
    entry_point = "main.js",
    visibility = ["//visibility:public"],
)

vitest_bin.vitest_test(
    name = "patka_test",
    args = ["run"],
    chdir = package_name(),
    data = glob(["*.ts"]) + [
        "tsconfig.json",
        "//:package_json",
        "//:node_modules/rxjs",
        "//:node_modules/vitest",
    ],
)
